### ISSUE TITLE
Upgrade RPC Issues 0.12

### ISSUE THREAD

**Issue by daygle** [zetacoin/zetacoin#15]
Ever since upgrading the Zetacoin wallet to 0.12 I'm experiencing RPC connection drops/failing to connect to RPC. It seems the wallet work ok but at times it looses connection.

I am going to revert back to 11.3.5 which I didn't experience any of these issues.

**Comment by RepoBike** [comment]
I am having the same problem with mine.

**Comment by daygle** [comment]
I believe the issue has been sorted with an update since I logged this case.

Closing.
