### ISSUE TITLE
Unable to pull latest version.

### ISSUE THREAD

**Issue by p3yot3** [zetacoin/zetacoin#7]
When trying to retrieve the latest version I get:

"remote: Counting objects: 24891, done.
remote: Total 24891 (delta 6305), reused 6305 (delta 6305), pack-reused 18586
Receiving objects: 100% (24891/24891), 19.91 MiB | 462.00 KiB/s, done.
Resolving deltas: 100% (18785/18785), completed with 985 local objects.
From https://github.com/zetacoin/zetacoin
 + c0dc005...35faf15 master     -> origin/master  (forced update)
 * [new branch]      0.11       -> origin/0.11
 * [new branch]      0.9-master -> origin/0.9-master
 * [new tag]         v0.11.2.1  -> v0.11.2.1
 * [new tag]         v0.11.2.0rc1 -> v0.11.2.0rc1

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'rig@rig.(none)')"

Is this repo ready?

**Comment by zetacoin** [comment]
Try deleting old local repository and using git clone instead of git pull.

**Comment by p3yot3** [comment]
That worked, thanks.
